import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Footer from '../components/Footer'
import Header from '../components/header'
import styles from '../styles/Base.module.css'

const About: NextPage = () => {

  const pageTitle: string = "About - Julian Kamphausen";

  return (
    <div className={styles.container}>
      <Head>
        <title>{pageTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={styles.main}>
        <h1>About</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque inventore vero sapiente autem repellendus eos esse, delectus harum non distinctio ea nulla accusamus amet, pariatur beatae consectetur et itaque nam!</p>
        <Image
          className={styles.authorImage}
          src="/jkamphausen-scaled.jpg"
          alt="Picture of the author"
          width={256}
          height={256}
        // blurDataURL="data:..." automatically provided
        // placeholder="blur" // Optional blur-up while loading
        />
        <section className={styles.listSection}>
          <h2>Experience</h2>
          <ul>
            <li><span className={styles.annotation}>upcoming</span></li>
          </ul>
        </section>
      </main>

      <Footer />
    </div>
  )
}

export default About
